server:
  name: "yunjing-user-server"
#  host: "0.0.0.0"
  port: 35002
etcd:
  name: "yunjing/user"
  host: "127.0.0.1"
  port: 2379
zap:
  debugFileName: "/logs/debug/debug.log"
  infoFileName: "/logs/info/info.log"
  warnFileName: "/logs/error/error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
mysql:
  username: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  dbname: "test_db"
jaeger:
  host: "127.0.0.1"
  port: 6831
redis:
  host: "127.0.0.1"
  port: 6379
  password: 123456
rabbitmq:
  host: "127.0.0.1"
  port: 5672
  username: "guest"
  password: "guest"